name: Deploy App
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t codingmaven1/test-react -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true codingmaven1/test-react npm test
      - run: docker build -t codingmaven1/multi-app-client ./client
      - run: docker build -t codingmaven1/multi-app-nginx ./nginx
      - run: docker build -t codingmaven1/multi-app-server ./server
      - run: docker build -t codingmaven1/multi-app-worker ./worker
      - run: docker push codingmaven1/multi-app-client
      - run: docker push codingmaven1/multi-app-nginx
      - run: docker push codingmaven1/multi-app-server
      - run: docker push codingmaven1/multi-app-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-multi
          environment_name: Dockermulti-env
          existing_bucket_name: elasticbeanstalk-ap-south-1-824815708558
          region: ap-south-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip